# html lang
language: zh

# main menu navigation
menu:
  Home: /
  # About: /about
  # Contact: /contact
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/panic.css

# scripts loaded in the end of the body
scripts:
- /js/panic.js
